<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>JogoDaForca</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>

		<ApplicationTitle>Jogo da Forca</ApplicationTitle>
		<ApplicationId>com.seunome.jogodaforca</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0.0</ApplicationDisplayVersion>
	</PropertyGroup>

	<ItemGroup>
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="512,512" />
	</ItemGroup>

	<ItemGroup>
		<MauiImage Include="Resources\Images\*.png" />
		<MauiImage Include="Resources\Images\*.jpg" />
		<MauiImage Include="Resources\Images\*.gif" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
</Project>
